info = {"message": "update test_import", "commit": "88730eb4ba8372eb776768cb15ccbd0a53e2e205", "date": "2023-05-18 10:30:35 +0700", "branch": "main", "version": "88730eb+dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
