info = {"message": "add test_import", "commit": "deb9225ba3a4a2cc7fd35a7b4753759f6e0923ca", "date": "2023-04-26 17:59:42 +0700", "branch": "main", "version": "deb9225"}

# This file is automatically generated by version.py
# Do not include it to git!
