info = {"message": "Update test", "commit": "87288c9c97f13b81afb66edfa1eac7afb2fbf279", "date": "2023-05-24 17:05:00 +0700", "branch": "dev", "version": "87288c9+dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
