# name: Selenium Test CI

# on:
#   push:
#     branches: ['dev']
#   pull_request:
#     branches: ['dev']

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.10.8

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -e .
#           pip install -r requirements.txt
#           pip install -r deploy/requirements.txt
#           pip install -r deploy/requirements-test.txt
#           pip install pytest-html
          
#       - name: Run tests
#         run: |
#           cd label_studio
#           python manage.py runserver
#           python -m pytest test_selenium --html=report.html -vv -n auto --self-contained-html
        
#       - name: Upload Test Report
#         uses: actions/upload-artifact@v2
#         with:
#           name: Test Report
#           path: label_studio/report.html


