name: Selenium Test CI

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.8

      - name: Install dependencies
        run: |
          sudo apt-get install -y chromium-browser
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r deploy/requirements.txt

      - name: Run Selenium tests
        run: |
          cd label_studio
          python -m pytest -v -s -U http://localhost:8080/ test_selenium/test_signin.py
          

